import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { WatchHistoryAddRequest, WatchHistoryItem } from "@/src/dto/media";
import { ApiResponse } from "@/src/dto/api";
import {
  getCachedDataOnly,
  invalidateCache,
  setCachedData,
} from "@/src/lib/cache";

const VALID_STREAMS = new Set([
  "syntherionmovie",
  "ironlinkmovie",
  "dormannumovie",
  "nanovuemovie",
  "syntheriontv",
  "ironlinktv",
  "dormannutv",
  "nanovuetv",
]);

export async function GET(req: Request) {
  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return NextResponse.json(
        { error: "Missing or Invalid Token" },
        { status: 401 },
      );
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      { global: { headers: { Authorization: authHeader } } },
    );

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Cache watch history for 2 minutes (same TTL as watchlist)
    const cacheKey = `watch-history:${user.id}`;
    let data = await getCachedDataOnly<WatchHistoryItem[]>(cacheKey);

    if (!data) {
      const { data: dbData, error } = await supabase
        .from("watch_history")
        .select("*")
        .eq("user_id", user.id)
        .order("watched_at", { ascending: false })
        .limit(10);

      if (error) throw error;
      data = dbData as WatchHistoryItem[];
    }

    // Use ApiResponse wrapper for consistent response format
    const response: ApiResponse<WatchHistoryItem[]> = {
      success: true,
      data,
    };

    return NextResponse.json(response, { status: 200 });
  } catch (err: any) {
    console.error("Error fetching watch history:", err.message);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}

export async function POST(req: Request) {
  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      console.warn(
        "⚠️ Watch History: Blocked request with missing/invalid token",
      );
      return NextResponse.json(
        { error: "Missing or Invalid Token" },
        { status: 401 },
      );
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      { global: { headers: { Authorization: authHeader } } },
    );

    const body: WatchHistoryAddRequest = await req.json();
    const {
      tmdb_id,
      media_type,
      stream_id,
      title,
      poster_path,
      release_date,
      season_number,
      episode_number,
      episode_name,
      episode_length,
      duration_sec = 0,
    } = body;

    // Get user_id from authenticated user
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user_id = user.id;

    if (!user_id || !tmdb_id || !title || !media_type || !stream_id) {
      console.error("❌ Watch History: Missing required fields in payload");
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 },
      );
    }

    if (!VALID_STREAMS.has(stream_id)) {
      console.error(`❌ Watch History: Invalid stream source: ${stream_id}`);
      return NextResponse.json({ error: "Invalid Stream ID" }, { status: 400 });
    }

    // 1. Check for existing record first
    const { data: existing } = await supabase
      .from("watch_history")
      .select("id, duration_sec, season_number, episode_number")
      .match({ user_id, tmdb_id, media_type })
      .maybeSingle();

    let finalDuration = duration_sec;

    // --- Duration Logic ---
    if (existing) {
      const isSameContext =
        media_type === "movie" ||
        (existing.season_number === season_number &&
          existing.episode_number === episode_number);

      if (isSameContext) {
        finalDuration += existing.duration_sec || 0;
      } else {
      }
    } else {
    }

    const payload = {
      user_id,
      tmdb_id,
      media_type,
      stream_id,
      title,
      poster_path,
      release_date,
      season_number,
      episode_number,
      episode_name,
      episode_length,
      duration_sec: finalDuration,
      watched_at: new Date().toISOString(),
    };

    let query;

    if (existing?.id) {
      // Update existing record using ID selector

      query = supabase
        .from("watch_history")
        .update(payload)
        .eq("id", existing.id);
    } else {
      // Insert new record (ID is generated by DB)

      query = supabase.from("watch_history").insert(payload);
    }

    const { data, error } = await query.select().single();

    if (error) {
      console.error("❌ Supabase Write Error:", error.message);
      throw error;
    }

    // Instead of invalidating, fetch fresh data and update cache
    const { data: freshHistory, error: fetchError } = await supabase
      .from("watch_history")
      .select("*")
      .eq("user_id", user_id)
      .order("watched_at", { ascending: false })
      .limit(10);

    if (!fetchError && freshHistory) {
      // Update watch-history cache with fresh data
      await setCachedData(
        `watch-history:${user_id}`,
        freshHistory as WatchHistoryItem[],
        120, // 2 minutes TTL
      );
    }

    // Profile cache still needs invalidation as it has more complex data
    await invalidateCache(`profile:${user_id}`);

    return NextResponse.json({ success: true, data }, { status: 200 });
  } catch (err: any) {
    console.error("🔥 Critical Error in Watch History API:", err.message);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
